franka:
  joint1_position_controller:
    type: "position_controllers/JointPositionController"
    joint: panda_joint1

  joint2_position_controller:
    type: "position_controllers/JointPositionController"
    joint: panda_joint2

  joint3_position_controller:
    type: "position_controllers/JointPositionController"
    joint: panda_joint3

  joint4_position_controller:
    type: "position_controllers/JointPositionController"
    joint: panda_joint4

  joint5_position_controller:
    type: "position_controllers/JointPositionController"
    joint: panda_joint5

  joint6_position_controller:
    type: "position_controllers/JointPositionController"
    joint: panda_joint6

  joint7_position_controller:
    type: "position_controllers/JointPositionController"
    joint: panda_joint7

gazebo_ros_control:
  pid_gains:
    panda_joint1: {p: 100.0, i: 1, d: 10}
    panda_joint2: {p: 100.0, i: 1, d: 10}
    panda_joint3: {p: 100.0, i: 1, d: 10}
    panda_joint4: {p: 100.0, i: 1, d: 10}
    panda_joint5: {p: 100.0, i: 1, d: 10}
    panda_joint6: {p: 100.0, i: 1, d: 10}
    panda_joint7: {p: 100.0, i: 1, d: 10}
